# Property used on app startup to check the config server status
configserver:
    name: configserver
    status: Connected to the configserver git config server!

spring:
    cloud:
        loadbalancer:
            retry: 
                enabled: true
        services:
            registrationMethod: route
discovery:
    registry:
        user: admin
        password: admin
        host: localhost
        port: 8761

eureka:
    server:
        # When the eureka server starts up it tries to fetch all the registry information from 
        # the peer eureka nodes. This operation is retried 5 times for each peer (configurable 
        # by eureka.server.numberRegistrySyncRetries). If for some reason this operation fails, 
        # the server does not allow clients to get the registry information for 5min 
        # (configurable by eureka.server.getWaitTimeInMsWhenSyncEmpty)
        waitTimeInMsWhenSyncEmpty: 0
        # Eureka Server has a protection feature: in case a certain number of Instances fail to 
        # send heartbeats in a determined time interval, the Server will not remove them from 
        # the registry. It considers that a network partition occurred and will wait for these 
        # Instances to come back. This feature is very useful in Cloud deploys and can be turned 
        # off for collocated Services in a private data center.
        enableSelfPreservation: false
    instance:
        prefer-ip-address: false
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.context-path}/info
        health-check-url-path: ${management.context-path}/health
        metadata-map:
            profile: ${spring.profiles.active}
            version: ${info.project.version}
    client:
        enabled: true
        healthcheck:
            enabled: true
        #fetch-registry: true
        #register-with-eureka: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
        serviceUrl:
            defaultZone: http://myeurekaserver.cfapps.io/regs/eureka/

management:
    context-path: /management
    security:
        enabled: false
    health:
        jms:
            enabled: false
        config:
            enabled: false
endpoints:
    health:
        sensitive: false
